### ISSUE TITLE
Potentially document automated migration for v8

### ISSUE THREAD

**Issue by timtebeek** [jobrunr/website#38]
hi all; congrats on nearing the v8 release! I'd read through the migration guide and saw that some of the migration steps can already be achieved by running the below recipe, after adding a local `rewrite.yml` file and calling:

```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.jobrunr.migration.MigrateToJobRunrV8
```

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.jobrunr.migration.MigrateToJobRunrV8
displayName: Migrate to JobRunr v8
description: Applies breaking changes for JobRunr v8 upgrade.
recipeList:
  - org.jobrunr.migration.MigratePropertiesToJobRunrV8

  - org.openrewrite.java.ChangeMethodName:
      methodPattern: 'org.jobrunr.jobs.JobBuilder runAfter(..)'
      newMethodName: runAfterSuccessOf
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: 'org.jobrunr.dashboard.JobDashboardProgressBar increaseByOne()'
      newMethodName: incrementSucceeded
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: 'org.jobrunr.dashboard.JobDashboardProgressBar getProgress()'
      newMethodName: getProgressAsPercentage

  - org.openrewrite.java.ChangePackage:
      oldPackageName: org.jobrunr.exposed.transaction.sql
      newPackageName: org.jobrunr.kotlin.storage.sql.exposed
      recursive: true

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.jobrunr.jobs.JobParameterNotDeserializableException
      newFullyQualifiedTypeName: org.jobrunr.jobs.exceptions.JobParameterNotDeserializableException

---
type: specs.openrewrite.org/v1beta/recipe
name: org.jobrunr.migration.MigratePropertiesToJobRunrV8
displayName: Migrate properties to JobRunr v8
description: Applies breaking changes for JobRunr v8 property upgrades.
recipeList:
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.database.skip-create
      newPropertyKey: jobrunr.database.skip-create
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.database.table-prefix
      newPropertyKey: jobrunr.database.table-prefix
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.database.database-name
      newPropertyKey: jobrunr.database.database-name
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.database.datasource
      newPropertyKey: jobrunr.database.datasource
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.database.type
      newPropertyKey: jobrunr.database.type
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.jobs.default-number-of-retries
      newPropertyKey: jobrunr.jobs.default-number-of-retries
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.jobs.retry-back-off-time-seed
      newPropertyKey: jobrunr.jobs.retry-back-off-time-seed
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.jobs.metrics.enabled
      newPropertyKey: jobrunr.jobs.metrics.enabled
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.job-scheduler.enabled
      newPropertyKey: jobrunr.job-scheduler.enabled
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.enabled
      newPropertyKey: jobrunr.background-job-server.enabled
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.worker-count
      newPropertyKey: jobrunr.background-job-server.worker-count
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.poll-interval-in-seconds
      newPropertyKey: jobrunr.background-job-server.poll-interval-in-seconds
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.delete-succeeded-jobs-after
      newPropertyKey: jobrunr.background-job-server.delete-succeeded-jobs-after
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.permanently-delete-deleted-jobs-after
      newPropertyKey: jobrunr.background-job-server.permanently-delete-deleted-jobs-after
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.background-job-server.metrics.enabled
      newPropertyKey: jobrunr.background-job-server.metrics.enabled
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.dashboard.enabled
      newPropertyKey: jobrunr.dashboard.enabled
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.dashboard.port
      newPropertyKey: jobrunr.dashboard.port
  - org.openrewrite.properties.ChangePropertyKey:
      oldPropertyKey: org.jobrunr.miscellaneous.allow-anonymous-data-usage
      newPropertyKey: jobrunr.miscellaneous.allow-anonymous-data-usage
```
I hope that's helpful to someone already; some of the other steps can likely also be automated quite easily, but would require some dedicated imperative recipes I think, optionally added to for instance a migration module under jobrunr/jobrunr  Didn't know if that effort would be appreciated, so figured to stop here for now.

All the best!
